version: '3'

services:
  db:
    image: mysql:5.7
    volumes: 
      - to_do_app_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - 3306:3306
  web:
    container_name: to_do_app
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/src/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  to_do_app_data:
