version: 2.1

orbs: 
  ruby: circleci/ruby@2.0.1
  node: circleci/node@5.1.0

# このプロジェクトで実行するジョブの定義
jobs: 
  build-and-test:
    docker:
      - image: cimg/ruby:3.2.1-browsers
        environment:
          - RAILS_ENV: 'test'
          - DATABASE_HOST: db
      - image: circleci/mysql:5.7


    working_directory: ~/repo
    steps: 
      - setup_remote_docker
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Bundle install
          command: |
            bundle install --path ./vendor/bundle
      - save_cache:
          paths: 
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run: 
          name: Build and test
          command: |
            docker-compose build --quiet --no-cache
            docker-compose up -d
      - run:
          name: db接続を待機
          command: sleep 10
      - run: 
          name: create
          command: |

            docker-compose run web bash -c "pwd && ls && bundle exec rails db:create"
            docker-compose run web bundle exec rails db:migrate
            docker-compose run web yarn install --check-files
            docker-compose run web bundle exec rails webpacker:compile
            docker-compose run web bundle exec rspec
      - run: 
          name: compose down
          command: |
            docker-compose down -v
      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

workflows:
  build-and-test:
    jobs:
      - build-and-test
