version: 2.1

orbs: 
  ruby: circleci/ruby@2.0.1
  node: circleci/node@5.1.0
  aws-cli: circleci/aws-cli@4.0.0

# このプロジェクトで実行するジョブの定義
jobs: 
  build-and-test:
    docker:
      - image: cimg/ruby:3.2.1-browsers
        environment:
          - RAILS_ENV: 'test'
          - DATABASE_HOST: db
      - image: circleci/mysql:5.7


    working_directory: ~/repo
    steps: 
      - setup_remote_docker
      - checkout
      - aws-cli/install
      - aws-cli/setup
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Bundle install
          command: |
            bundle install --path ./vendor/bundle
      - save_cache:
          paths: 
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run: 
          name: docker-compose build 
          command: |
            docker-compose build --quiet --no-cache
            docker-compose up -d
      - run:
          name: Waiting for db connection
          command: sleep 10
      - run: 
          name: DB create
          command: |
            docker-compose run web bundle exec rails db:create
            docker-compose run web bundle exec rails db:migrate
      - run: 
          name: javascript
          command: |
            docker-compose run web yarn install --check-files
            docker-compose run web bundle exec rails webpacker:compile
      - run: 
          name: RSpec test
          command: |
            docker-compose run web bundle exec rspec
      - run: 
          name: RSpec test
          command: |
            aws ecr get-login-password --region ${AWS_DEFAULT_LEGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com
            docker tag to_do_app:latest ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_LEGION}.amazonaws.com/to_do_app:latest
            docker push 943726312182.dkr.ecr.ap-northeast-1.amazonaws.com/to_do_app:latest
      - run: 
          name: compose down
          command: |
            docker-compose down -v
      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

workflows:
  build-and-test:
    jobs:
      - build-and-test
