version: 2.1

orbs: 
  ruby: circleci/ruby@2.0.1
  node: circleci/node@5.1.0

# このプロジェクトで実行するジョブの定義
jobs: 
  build-and-test:
    docker:
      - image: cimg/ruby:3.2.1-browsers
        environment:
          - RAILS_ENV: 'test'
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
          - MYSQL_ROOT_HOST: '%'

    working_directory: ~/repo
    steps: 
      - setup_remote_docker
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Bundle install
          command: |
            bundle install --path ./vendor/bundle
      - save_cache:
          paths: 
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: '1.29.2'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run: 
          name: Build and test
          command: |
            docker-compose build --quiet --no-cache
            docker-compose up -d
            docker-compose ps
            docker-compose logs db
      - run: 
          name: ps
          command: |
            docker-compose ps
            docker-compose logs db
      - run: 
          name: create
          command: |
            docker-compose run web bundle exec rails db:create
            docker-compose run web bundle exec rails db:migrate
            docker-compose run web yarn install --check-files
            docker-compose run web bundle exec rails webpacker:compile
            docker-compose run web bundle exec rspec
      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

workflows:
  build-and-test:
    jobs:
      - build-and-test
